### PR TITLE
Create forkme.py

### PR DESCRIPTION
**Pull request by PPPDUD**

### CODE REVIEW

**Comment by PPPDUD** [comment]
@JaydenDev

**Comment by PPPDUD** [comment]
You have 6 PRs which you haven't responded to.

**Comment by jdev082** [comment]
> You have 6 PRs which you haven't responded to.

I'm more focused on my actual projects. Try helping out there.

**Comment by PPPDUD** [comment]
Okay.

**Comment by jdev082** [comment]
Contribute to Catalyst

**Comment by PPPDUD** [comment]
I might consider it if I see something that might want some change.

**Comment by jdev082** [comment]
Help convert from tailwind to css

**Comment by PPPDUD** [comment]
I would, but I am not really familiar with Tailwind. I might try, though.

**Pull request merged**
